bind m set-option mouse\; display-message "Mouse is now #{?mouse,on,off}"
setw -g mouse on
set -g extended-keys on

# add focus events for claude focus tracking
set -g focus-events on

# show terminal bells for offscreen panels
set-window-option -g monitor-bell on
set -g visual-bell on
set -g bell-action other
 
#use F9 for the tmux key
#unbind C-b
set-option -g prefix F9
bind-key F9 send-prefix
 
#horiz or ver split
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
 
unbind z
bind f resize-pane -Z

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-features ",*:RGB"

set -g window-status-current-style fg=black,bg=blue
